#-*- coding: utf-8 -*-

{
	"name": "EPS Sequence",
	"version": "1.0", 
	"depends": [
		'base','base_suspend_security'
	],
	"author": "Tunas Honda",
	"category": "Utility",
	"website": "https://www.tunasgroup.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"summary": "This is the DMS Sequence module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}